config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users, only: :show
  resources :blogs do
    resources :users, only: :show
    resources :blog_comments, only: %i[create destroy]
  end
  resources :movies do
    resources :users, only: :show
    resources :movie_comments, only: %i[create destroy]
  end
  resources :posts do
    resources :users, only: :show
    resources :comments, only: %i[create destroy]
  end
  post 'like/:id', to: 'likes#create', as: 'create_like'
  delete 'like/:id', to: 'likes#destroy', as: 'destroy_like'

  post 'movie_like/:id', to: 'movie_likes#create', as: 'create_movie_like'
  delete 'movie_like/:id', to: 'movie_likes#destroy', as: 'destroy_movie_like'

  post 'blog_like/:id', to: 'blog_likes#create', as: 'create_blog_like'
  delete 'blog_like/:id', to: 'blog_likes#destroy', as: 'destroy_blog_like'
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_rich_text :body
    has_many_attached :images
    belongs_to :user
    has_many :blog_comment,dependent: :destroy
    has_many :blog_likes
    has_many :blog_liked_users, through: :blog_likes, source: :user
    
    with_options presence: true do
        validates :title
        validates :body,length: { minimum: 141 }
    end


end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/blog_like.rb
class BlogLike < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :movie
  has_many :movie_liked_users, through: :movie_likes, source: :user
  has_many :movie_likes
  has_many :movie_comments, dependent: :destroy
  belongs_to :user
  has_many :movie_likes

  with_options presence: true do
        validates :title
        validates :introduction
    end
    validates :movie, presence: true, blob: { content_type: :video } 

  end

app/models/movie_comment.rb
class MovieComment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie_like.rb
class MovieLike < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  validates :content,length: { maximum: 140 }, presence: true

  validates :images, blob: { content_type: :image } 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :posts
  has_many :likes
  has_many :comments, dependent: :destroy
  has_many :movie_likes
  has_many :movies
  has_many :movie_comments, dependent: :destroy
  has_many :blogs, dependent: :destroy
  has_many :blog_likes
  has_many :blog_comments, dependent: :destroy

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  def movie_liked_by?(movie_id)
    movie_likes.where(movie_id: movie_id).exists?
  end

  def blog_liked_by?(blog_id)
    blog_likes.where(blog_id: blog_id).exists?
  end

  with_options presence: true do
    validates :nickname
    validates :mania_histry, format: { with: /\A[0-9]+\z/ }
    validates :enjoy_point
    validates :email
    validates :password, length: { minimum: 6 }
  end

  validate :image_presence

  def image_presence
    if image.attached?
      if !image.blob.content_type.in?(%('image/jpeg image/png'))
        errors.add(:image, 'にはjpegまたはpngファイルを添付してください')
      end
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ update new create edit update destroy]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.includes(:user)
    @blog_like = BlogLike.new
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @blog_comment = BlogComment.new
    @blog_comments = @blog.blog_comment.order(id: 'DESC')
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "ブログの投稿が完了しました。" }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "ブログの内容を編集しました。" }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "ブログを消去しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title,:body).merge(user_id: current_user.id)

    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :post_params

  def create
    Like.create(user_id: current_user.id, post_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, post_id: params[:id]).destroy
  end

  private

  def post_params
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new update create edit update destroy]
  before_action :find_post, only: %i[edit update show destroy]

  def index
    @posts = Post.includes(:user).order(id: 'DESC')
    @like = Like.new
  end

  def new
    @post = Post.new

  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(id: 'DESC')
  end

  def create
    @post = current_user
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path, notice: '投稿に成功しました'
    else
      redirect_to new_post_path, notice: '投稿に失敗しました'
    end
  end

  def edit; end

  def update
    @post.update(post_params)
    redirect_to root_path
  end

  def destroy
    if @post.destroy
      redirect_to root_path, alert: '投稿を削除しました'
    else
      redirect_to root_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, { images: [] }).merge(user_id: current_user.id)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def force_redirect_unless_my_post
    return redirect_to root_path, alert: '権限がありません' if @post.user != current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_likes_helper.rb
module BlogLikesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movie_likes_helper.rb
module MovieLikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<% if user_signed_in? %>
    <h3>いいね件数: <%= blog.blog_likes.count %></h3>

<% else %>
    <h3>いいね件数: <%= blog.blog_likes.count %></h3>
<% end %>

<% if user_signed_in? %>
      <div class="like">
       <div class = 'like-button'>
          <% if current_user.blog_liked_by?(blog.id) %>
                <td><%= link_to 'いいねを外す', destroy_blog_like_path(blog), class: "like-link", method: :DELETE,remote: true %></td>
                <i class="fa fa-heart unlike-btn"></i>
            <% else %>
                <td><%= link_to 'いいね', create_blog_like_path(blog), class: "like-link", method: :post, remote: true %></td>
                <i class="fa fa-heart like-btn"></i>
          <% end %>
       </div>
    </div>
<% end %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :タイトル %>
  <%= form.text_field :title %>
</div>

  
  <div class="field">
    <%= form.label :記事内容 %>
    <%= form.rich_text_area :body %>
  </div>
  

  <div class="actions">
  <div class = 'submit-block'>
  <%= form.submit '投稿する', class:"button"%>
  </div>

  </div>
<% end %>

app/views/blogs/_user-about.html.erb
<div class="user-about">
    <div class="image">
        <% if blog.user.image.attached? %>
            <%= image_tag blog.user.image %>
        <% else %>
            <%= image_tag 'no.user.png' %>
        <% end %>
    </div>
    <div class="profile">
            <div class="name-history">
                <div class="name">
                    <%= blog.user.nickname %>
                </div>
                <div class="mania-histry">
                    <%= "趣味歴:#{blog.user.mania_histry}年" %>
                </div>
            </div>
        <div class="enjoy-point">
            <%= "楽しいポイント#{blog.user.enjoy_point}"%>
        </div>
    </div>
</div>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="content-wrapper">
  <div class="content-block">
      <% @blogs.each do |blog| %>
      <div class="content">
        <%= render 'user-about', blog: blog%>
            <div class="text">
                    <div class="title">
                        <h3>タイトル: <%= blog.title %></h3>
                    </div>
            <h2><%= truncate(strip_tags(blog.body.to_s),length: 14) %></h2></h2><%= link_to "コメントor続きをよむ", "/blogs/#{blog.id}" %>
            </div>

          <div class="action-menu">
                <div id="blog_<%= blog.id %>">
                    <%= render 'blog', blog: blog %>
                </div>
                    <h3>コメント件数: <%= blog.blog_comment.count %></h3>
                    <%= link_to "この方について", blog_user_path(blog,blog.user.id) %>

                <% if user_signed_in?%>
                    <div class='user-action'>
                        <% if current_user.id == blog.user.id %>
                            <%= link_to "編集", edit_blog_path(blog) %>
                            <%= link_to "削除", blog_path(blog), method: :delete %>
                        <% end %>
                    </div>
                    <% end %>
            </div>
        </div>
      <% end %>
    </div>
      <div class="sidebar">
           <%= render 'shared/menu'%>
      </div> 
  </div> 

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="content">
  <%= render 'user-about', blog: @blog%>

        <div class="text">
          <div class="title">
              <h3>タイトル: <%= @blog.title %></h3>
          </div>
        <p><%= @blog.body %></p>
       
        </div>

      <div class="action-menu">
            <% if user_signed_in? %>
                <div class="like">
                    <div id="blog_<%= @blog.id %>">
                    <%= render @blog, blog: @blog %>
                  </div>

                  <h3>コメント件数: <%= @blog.blog_comment.count %></h3>
                  <%= link_to "この方について", blog_user_path(@blog,@blog.user.id) %>

                  <div class="comment">
                  <% if user_signed_in? %>
                  <%= render partial: 'comments/form', locals: { comments: @comments } %>
                      <% @blog_comments.each do |blog_comment| %>
                            <div class="comment-user">
                              <tr>
                                <td><%= blog_comment.user.nickname %>:  </td>
                                <td><%= blog_comment.blog_comment %></td>
                                <td><%= link_to "削除", blog_blog_comment_path(@blog, blog_comment), method: :delete %></td>
                              </tr>
                            </div>
                      <% end %>
                  <% end %>
                <% else %>
                  <h3>コメント件数: <%= @blog.blog_comment.count %></h3>
            <% end %>
          </div>
              </div>
      </div>
</div>

app/views/likes/create.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render @post) %>'

app/views/likes/destroy.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render @post) %>'

app/views/posts/_form.html.erb
<div class ='post-content'>
   <%= form_with model: @post, local: true  do |f| %>
         <%= f.text_area :content, :placeholder => "いまどんなカンジ？"%>
         <%= f.file_field :images, multiple: true%>
      <div class = 'submit-block'>
         <%= f.submit '投稿する', class:"button"%>
      </div>
   <% end %>
</div>

app/views/posts/_post.html.erb
<% if user_signed_in? %>
    <h3>いいね件数: <%= post.likes.count %></h3>

<% else %>
    <h3>いいね件数: <%= post.likes.count %></h3>
<% end %>

<% if user_signed_in? %>
      <div class="like">
        <div class = 'like-button'>
          <% if current_user.liked_by?(post.id) %>
                <td><%= link_to 'いいねを外す', destroy_like_path(post), class: "like-link", method: :DELETE,remote: true %></td>
                <i class="fa fa-heart unlike-btn"></i>
            <% else %>
                <td><%= link_to 'いいね', create_like_path(post), class: "like-link", method: :post, remote: true %></td>
                <i class="fa fa-heart like-btn"></i>
          <% end %>
       </div>
    </div>
<% end %>

app/views/posts/_user-about.html.erb
<div class="user-about">
    <div class="image">
        <% if post.user.image.attached? %>
            <%= image_tag post.user.image %>
        <% else %>
            <%= image_tag 'no.user.png' %>
        <% end %>
    </div>
    <div class="profile">
            <div class="name-history">
                <div class="name">
                    <%= post.user.nickname %>
                </div>
                <div class="mania-histry">
                    <%= "趣味歴:#{post.user.mania_histry}年" %>
                </div>
            </div>
        <div class="enjoy-point">
            <%= "楽しいポイント#{post.user.enjoy_point}"%>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="content-wrapper">
    <div class="content-block">
        <% @posts.each do |post| %>
        <div class="content">
            <%= render 'user-about', post: post %>
       <div class="text">
        <h2><%= truncate(post.content, length:15) %></h2><%= link_to "コメントor続きをよむ", "/posts/#{post.id}" %>
    </div>
        <% if post.images.attached? %>
            <% post.images.each do |image| %>
                <div class = 'images'>
                    <%= image_tag image.variant(resize: "1280x720"), class: "content-image" %>
                </div>
            <% end %>
        <% end %>

         <div class="action-menu">
          
         <div id="post_<%= post.id %>">
                <%= render 'post', post: post %>
            </div>
            <h3>コメント件数: <%= post.comments.count %></h3>
            <%= link_to "この方について", post_user_path(post,post.user.id) %>
                <div class="comment">
                </div>
                    <%if user_signed_in?%>
                        <div class = 'user-action'>
                            <% if current_user.id == post.user.id %>
                                 <%= link_to "編集", edit_post_path(post) %>
                                 <%= link_to "削除", post_path(post), method: :delete %>
                             <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
    
    <div class="sidebar">
        <%= render 'shared/menu'%>       
    </div>
</div>


    

app/views/posts/new.html.erb
<div>
<%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div class="content">
      <%= render 'user-about', post: @post %>

      <div class="text">
        <p><%= @post.content %></p>
      </div>
    <% if @post.images.attached? %>
         <% @post.images.each do |image| %>
            <div class = 'images'>
              <%= image_tag image %>
            </div>
         <% end %>
    <% end %>
    <div class="action-menu">

        <% if user_signed_in? %>
            <div class="like">
                  <div id="post_<%= @post.id %>">
                    <%= render @post, post: @post %>
                  </div>
            <% end %>
            <h3>コメント件数: <%= @post.comments.count %></h3>

              <div class="comment">
                <%if user_signed_in?%>
                  <%= form_for [@post, @comment] do |f| %>
                    <%= f.text_area :comment, size: "40x2" %>
                    <%= f.submit '送信', class: "btn-sm btn-primary" %>
                <% end %>
              </div>
          </div>
        <% end %>
        <% @comments.each do |comment| %>
          <div class="comment-user">
            <tr>
              <td><%= comment.user.nickname %>:</td>
              <td><%= comment.comment %></td>
              <td><%= link_to "削除", post_comment_path(@post, comment), method: :delete %></td>
            </tr>
          </div>
        <% end %>
    </div>
</div>