config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users, only: :show
  resources :blogs do
    resources :users, only: :show
    resources :blog_comments, only: %i[create destroy]
  end
  resources :movies do
    resources :users, only: :show
    resources :movie_comments, only: %i[create destroy]
  end
  resources :posts do
    resources :users, only: :show
    resources :comments, only: %i[create destroy]
  end
  post 'like/:id', to: 'likes#create', as: 'create_like'
  delete 'like/:id', to: 'likes#destroy', as: 'destroy_like'

  post 'movie_like/:id', to: 'movie_likes#create', as: 'create_movie_like'
  delete 'movie_like/:id', to: 'movie_likes#destroy', as: 'destroy_movie_like'

  post 'blog_like/:id', to: 'blog_likes#create', as: 'create_blog_like'
  delete 'blog_like/:id', to: 'blog_likes#destroy', as: 'destroy_blog_like'
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_rich_text :body
    has_many_attached :images
    belongs_to :user
    has_many :blog_comment,dependent: :destroy
    has_many :blog_likes
    has_many :blog_liked_users, through: :blog_likes, source: :user
    
    with_options presence: true do
        validates :title
        validates :body,length: { minimum: 141 }
    end


end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/blog_like.rb
class BlogLike < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :movie
  has_many :movie_liked_users, through: :movie_likes, source: :user
  has_many :movie_likes
  has_many :movie_comments, dependent: :destroy
  belongs_to :user
  has_many :movie_likes

  with_options presence: true do
        validates :title
        validates :introduction
    end
    validates :movie, presence: true, blob: { content_type: :video } 

  end

app/models/movie_comment.rb
class MovieComment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie_like.rb
class MovieLike < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  validates :content,length: { maximum: 140 }, presence: true

  validates :images, blob: { content_type: :image } 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :posts
  has_many :likes
  has_many :comments, dependent: :destroy
  has_many :movie_likes
  has_many :movies
  has_many :movie_comments, dependent: :destroy
  has_many :blogs, dependent: :destroy
  has_many :blog_likes
  has_many :blog_comments, dependent: :destroy

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  def movie_liked_by?(movie_id)
    movie_likes.where(movie_id: movie_id).exists?
  end

  def blog_liked_by?(blog_id)
    blog_likes.where(blog_id: blog_id).exists?
  end

  with_options presence: true do
    validates :nickname
    validates :mania_histry, format: { with: /\A[0-9]+\z/ }
    validates :enjoy_point
    validates :email
    validates :password, length: { minimum: 6 }
  end

  validate :image_presence

  def image_presence
    if image.attached?
      if !image.blob.content_type.in?(%('image/jpeg image/png'))
        errors.add(:image, 'にはjpegまたはpngファイルを添付してください')
      end
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ update new create edit update destroy]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.includes(:user)
    @blog_like = BlogLike.new
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @blog_comment = BlogComment.new
    @blog_comments = @blog.blog_comment.order(id: 'DESC')
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "ブログの投稿が完了しました。" }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "ブログの内容を編集しました。" }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "ブログを消去しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title,:body).merge(user_id: current_user.id)

    end
    
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: %i[new update create edit update destroy]
  before_action :find_movie, only: %i[edit update show destroy]

  def index
    @movies = Movie.includes(:user).order(id: 'DESC')
    @movie_like = MovieLike.new
  end

  def new
    @movie = Movie.new
  end

  def show
    @movie_comment = MovieComment.new
    @movie_comments = @movie.movie_comments.order(id: 'DESC')
  end

  def create
    @movie = current_user
    @movie = Movie.create(movie_params)
    if @movie.save
      redirect_to movies_path, notice: '投稿に成功しました'
    else
      redirect_to new_movie_path, notice: '投稿に失敗しました'
    end
  end

  def edit; end

  def update
    @movie.update(movie_params)
    redirect_to movies_path
  end

  def destroy
    if @movie.destroy
      redirect_to movies_path, alert: '投稿を削除しました'
    else
      redirect_to movies_path
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :introduction, :movie).merge(user_id: current_user.id)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end

  def force_redirect_unless_my_movie
    return redirect_to movies_path, alert: '権限がありません' if @movie.user != current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_likes_helper.rb
module BlogLikesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movie_likes_helper.rb
module MovieLikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/movies/_form.html.erb
<div class ='movie-content'>
<%= form_with model: @movie, local: true do |f| %>
    <p>title</p><%= f.text_field :title %> <br>
    <p>introduction</p><%= f.text_area :introduction %> <br>
    <p>movie</p><%= f.file_field :movie %> <br>
    <div class = 'submit-block'>
    <%= f.submit '投稿する', class:"button"%>
    </div>
    <% end %>
    </div>


    

app/views/movies/_movie.html.erb
<%if user_signed_in?%>
<h3>いいね件数: <%= movie.movie_likes.count %></h3>

<% else %>
<h3>いいね件数: <%= movie.movie_likes.count %></h3>

<% end %>

<% if user_signed_in? %>
      <div class="like">
        <div class = 'like-button'>
          <% if current_user.movie_liked_by?(movie.id) %>
          <td><%= link_to 'いいねを外す', destroy_movie_like_path(movie), class: "like-link", method: :DELETE,remote: true %></td>
                <i class="fa fa-heart unlike-btn"></i>
            <% else %>
            <td><%= link_to 'いいね', create_movie_like_path(movie), class: "like-link", method: :post,remote: true %></td>

                <i class="fa fa-heart like-btn"></i>
          <% end %>
       </div>
    </div>
<% end %>

app/views/movies/_user-about.html.erb
<div class="user-about">
                        <div class="image">
                          <% if movie.user.image.attached? %>
                            <%= image_tag movie.user.image %>
                          <% else %>
                            <%= image_tag 'no.user.png' %>
                          <% end %>
                      </div>

                    <div class="profile">
                      <div class="name-history">
                          <div class="name">
                              <%= movie.user.nickname %>
                          </div>
                          <div class="mania-histry">
                            <%= "趣味歴:#{movie.user.mania_histry}年" %>
                          </div>
                      </div>
                      <div class="enjoy-point">
                          <%= "楽しいポイント#{movie.user.enjoy_point}"%>
                      </div>
                  </div>
          </div>

app/views/movies/edit.html.erb
<div>
<h1>投稿を編集する</h1>
  <%= render 'form' %>

</div>

app/views/movies/index.html.erb
<div class="content-wrapper">
    <div class="content-block">
        <% @movies.each do |movie| %>
          <div class="content">
            <%= render 'user-about', movie: movie %>

          <div class="text">
                    <h2><%= truncate(movie.title, length:15) %></h2><%= link_to "コメントor続きをよむ", "/movies/#{movie.id}" %>
                    <h3><%= truncate(movie.introduction, length:15) %></h3>
                    <video src=<%= rails_blob_path(movie.movie) %> ,type='movie/mp4 movie/mov', controls>
            </div>
            
            <div class="action-menu">
                    <div id="movie_<%= movie.id %>">
                        <%= render 'movie', movie: movie %>
                    </div>
                      <h3>コメント件数: <%= movie.movie_comments.count %></h3>
                  <%= link_to "この方について", movie_user_path(movie,movie.user.id) %>

                  <% if user_signed_in?%>
                    <div class='user-action'>
                        <% if current_user.id == movie.user.id %>
                            <%= link_to "編集", edit_movie_path(movie) %>
                            <%= link_to "削除", movie_path(movie), method: :delete %>
                        <% end %>
                      </div>
                  <% end %>
                </div>
                </div>
              <% end %>
          </div>
            <div class="sidebar">
                 <%= render 'shared/menu'%>
            </div> 
        </div> 
      </div>
                        
                        

    

app/views/movies/new.html.erb
<div>
<h1>動画を投稿する</h1>
  <%= render 'form' %>

</div>

app/views/movies/show.html.erb
<div class="content">

  <%= render 'user-about', movie: @movie %>

<div class="text">
<p><%= @movie.title %></p>
<p><%= @movie.introduction %></p>
<video src=<%= rails_blob_path(@movie.movie) %> type="movie/mp4", controls></ｖ>

</div>

<div class="action-menu">
  <% if user_signed_in? %>
    <div class="like">
      <div id="movie_<%= @movie.id %>">
      <%= render @movie, post: @movie %>
      <% end %>
      </div>
   <h3>コメント件数: <%= @movie.movie_comments.count %></h3>
   <%= link_to "この方について", movie_user_path(@movie,@movie.user.id) %>

      <div class="comment">
        <%if user_signed_in?%>
          <%= form_for [@movie, @movie_comment] do |f| %>
            <%= f.text_area :movie_comment, size: "40x2" %>
            <%= f.submit '送信', class: "btn-sm btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
  

  <% @movie_comments.each do |movie_comment| %>
    <div class="comment-user">
      <tr>
        <td><%= movie_comment.user.nickname %>:</td>
        <td><%= movie_comment.movie_comment %></td>
        <td><%= link_to "削除", movie_movie_comment_path(@movie, movie_comment), method: :delete %></td>
      </tr>
    </div>
  <% end %>
</div>
    
    </div>
</div>

</div>