config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users, only: :show
  resources :blogs do
    resources :users, only: :show
    resources :blog_comments, only: %i[create destroy]
  end
  resources :movies do
    resources :users, only: :show
    resources :movie_comments, only: %i[create destroy]
  end
  resources :posts do
    resources :users, only: :show
    resources :comments, only: %i[create destroy]
  end
  post 'like/:id', to: 'likes#create', as: 'create_like'
  delete 'like/:id', to: 'likes#destroy', as: 'destroy_like'

  post 'movie_like/:id', to: 'movie_likes#create', as: 'create_movie_like'
  delete 'movie_like/:id', to: 'movie_likes#destroy', as: 'destroy_movie_like'

  post 'blog_like/:id', to: 'blog_likes#create', as: 'create_blog_like'
  delete 'blog_like/:id', to: 'blog_likes#destroy', as: 'destroy_blog_like'
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_rich_text :body
    has_many_attached :images
    belongs_to :user
    has_many :blog_comment,dependent: :destroy
    has_many :blog_likes
    has_many :blog_liked_users, through: :blog_likes, source: :user
    
    with_options presence: true do
        validates :title
        validates :body,length: { minimum: 141 }
    end


end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/blog_like.rb
class BlogLike < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :movie
  has_many :movie_liked_users, through: :movie_likes, source: :user
  has_many :movie_likes
  has_many :movie_comments, dependent: :destroy
  belongs_to :user
  has_many :movie_likes

  with_options presence: true do
        validates :title
        validates :introduction
    end
    validates :movie, presence: true, blob: { content_type: :video } 

  end

app/models/movie_comment.rb
class MovieComment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie_like.rb
class MovieLike < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  validates :content,length: { maximum: 140 }, presence: true

  validates :images, blob: { content_type: :image } 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :posts
  has_many :likes
  has_many :comments, dependent: :destroy
  has_many :movie_likes
  has_many :movies
  has_many :movie_comments, dependent: :destroy
  has_many :blogs, dependent: :destroy
  has_many :blog_likes
  has_many :blog_comments, dependent: :destroy

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  def movie_liked_by?(movie_id)
    movie_likes.where(movie_id: movie_id).exists?
  end

  def blog_liked_by?(blog_id)
    blog_likes.where(blog_id: blog_id).exists?
  end

  with_options presence: true do
    validates :nickname
    validates :mania_histry, format: { with: /\A[0-9]+\z/ }
    validates :enjoy_point
    validates :email
    validates :password, length: { minimum: 6 }
  end

  validate :image_presence

  def image_presence
    if image.attached?
      if !image.blob.content_type.in?(%('image/jpeg image/png'))
        errors.add(:image, 'にはjpegまたはpngファイルを添付してください')
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_likes_helper.rb
module BlogLikesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movie_likes_helper.rb
module MovieLikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_error_messages.html.erb
<% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>

app/views/shared/_footer.html.erb
<div id="footer">
    <p>©I made february 16th </p>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <div class="logo">
      <a href="/">INN</a>
      </div>
      <div class="link">
        <ul id ='nav'>
        <%if user_signed_in?%>
            <li>
               <%= link_to '新規投稿', new_post_path(@post) %>
            </li>

            <li>    
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>

            </li>
            
            <li>
            <%= link_to '動画投稿', new_movie_path %>
            </li>

            <li>
            <%= link_to '動画一覧', movies_path %>
            </li>
            <% else %>
            
            <li>    
            <%= link_to 'ログイン', new_user_session_path %>
        </li>

        <li>    
            <%= link_to '新規登録', new_user_registration_path %>
        </li>
            <% end %>
            

            
        </ul>
    </div>
  </div>

app/views/shared/_menu.html.erb
<div id="menu">
        <ul id ='nav'>
        <%if user_signed_in?%>
            <li>
               <%= link_to 'つぶやき投稿', new_post_path(@post) %>
            </li>
            
            <li>
            <%= link_to 'つぶやき一覧', root_path %>
            </li>

            <li>    
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>

            </li>
            
            <li>
            <%= link_to '動画投稿', new_movie_path %>
            </li>

            <li>
            <%= link_to '動画一覧', movies_path %>
            </li>

            <li>
            <%= link_to 'ブログ一覧', blogs_path %>
            </li>

            <li>
            <%= link_to 'ブログ投稿', new_blog_path %>
            </li>

          <li>
          <%= link_to "プロフ編集", edit_user_registration_path %>
        </li>

            <% else %>
            <li>    
            <%= link_to 'ログイン', new_user_session_path %>
        </li>

        <li>    
            <%= link_to '新規登録', new_user_registration_path %>
        </li>

        <li>
          <%= link_to '動画一覧', movies_path %>
        </li>

        <li>
        <%= link_to 'ブログ一覧', blogs_path %>
      </li>


            <% end %>
            

            
        </ul>
  </div>

app/views/shared/_toast.html.erb
<% if flash[:notice].present? %>
<div class ='toast'>
<div class="notice"><%= notice %></div>
</div>
<% end %>

<% if flash[:alert].present? %>
<div class ='toast'>
<div class="alert"><%= alert %></div>
</div>
<% end %>